### ISSUE TITLE
argc QApplication

### ISSUE THREAD

**Issue by Chocobozzz** [itay-grudev/SingleApplication#1]
[QApplication](http://doc.qt.io/qt-5/qapplication.html) takes the argc adress `&argc` whereas you send the `argc` value to QApplication.

**Comment by itay-grudev** [comment]
`&argc` means alias of the argument provided. Therefore the way I wrote it is correct. Am I not right?

**Comment by Chocobozzz** [comment]
I don't think so because I had segfault with the way you wrote, and after having added the `&` all is ok :p

From the doc "The data referred to by argc and argv must stay valid for the entire lifetime of the QApplication object". IMHO, the actual `argc` is send as a copy and is so it is deleted when the constructor ends so argc is not valid for the entire lifetime of the application. It's the reason why we have to send the reference of argc, and not just a copy.

**Comment by itay-grudev** [comment]
So you propose that this:
```
SingleApplication::SingleApplication(int, char *[]);
```
Is changed to this:
```
SingleApplication::SingleApplication(int&, char *[]);
```

**Comment by Chocobozzz** [comment]
Yes it is (as in QtSingleApplication).

**Comment by Chocobozzz** [comment]
Thanks to you for propose an elegant alternative to QtSingleApplication for Qt5 :)

**Comment by itay-grudev** [comment]
And Thank You for the fix!
