### ISSUE TITLE
Add a signal for passing command line (argc, argv)

### ISSUE THREAD

**Issue by FaTony** [itay-grudev/SingleApplication#11]
I really like what you've done but I can't use it because I need to pass command line of the 2nd instance to the 1st. Can this be added?

**Comment by itay-grudev** [comment]
Yes it can. This is a feature so many people want lately, that I will work on it tomorrow. I'll create an interface for communicating from the secondary instances to the primary one.

**Comment by itay-grudev** [comment]
Support for communication to the primary instance had been added in the new version `3.0a`.
