### ISSUE TITLE
Compiling in MSVC x64 broght some type errors

### ISSUE THREAD

**Issue by lucasm0ta** [itay-grudev/SingleApplication#12]
The error below appeared in the building phase:
`singleapplication.cpp(74): error C2664: 'BOOL GetUserNameW(LPWSTR,LPDWORD)' : cannot  convert argument 1 from 'char [257]' to 'LPWSTR'`

**Comment by itay-grudev** [comment]
What exactly?

**Comment by lucasm0ta** [comment]
Fix with the following code with the next one. 
> char username[UNLEN + 1];
// Specifies size of the buffer on input
DWORD usernameLength = sizeof( username );
if( GetUserName( username, &usernameLength ) ) {
    // usernameLength includes the null terminating character
    appData.addData( username, usernameLength - 1 );
 } else {
    appData.addData( QStandardPaths::standardLocations( QStandardPaths::HomeLocation).join("").toUtf8() );
}

The fix below. 

> wchar_t username[UNLEN + 1];
        // Specifies size of the buffer on input
        DWORD usernameLength = UNLEN + 1;
        if( GetUserName( username, &usernameLength ) ) {
            // usernameLength includes the null terminating character
            char buff[512];
            wcstombs(buff, username, 512);
            appData.addData( buff, 512);
        } else {
            appData.addData( QStandardPaths::standardLocations( QStandardPaths::HomeLocation ).join("").toUtf8() );
        }

**Comment by itay-grudev** [comment]
What exactly was the error you were getting?

**Comment by lucasm0ta** [comment]
Sorry, updated the description just after posting. This was the error:

singleapplication.cpp(74): error C2664: 'BOOL GetUserNameW(LPWSTR, LPDWORD)': cannot convert argument 1 from 'char [257]' to 'LPWSTR'

**Comment by lucasm0ta** [comment]
Sorry, updated the description just after posting. This was the error:

singleapplication.cpp(74): error C2664: 'BOOL GetUserNameW(LPWSTR, LPDWORD)': cannot convert argument 1 from 'char [257]' to 'LPWSTR'

**Comment by itay-grudev** [comment]
Woah! My code is using `GetUserName` and not `GetUserNameW`.

**Comment by itay-grudev** [comment]
The only think I don't like is the fixed size buffer, but I don't know what to do to make it smarter.

**Comment by itay-grudev** [comment]
I don't have a Windows machine atm, but can you verify that this works:

```cpp
        wchar_t username [ UNLEN + 1 ];
        // Specifies size of the buffer on input
        DWORD usernameLength = UNLEN + 1;
        if( GetUserName( username, &usernameLength ) ) {
            char buffer[512];
            size_t length = wcstombs( buffer, username, 512 );
            appData.addData( buffer, length );
        } else {
            appData.addData( QStandardPaths::standardLocations( QStandardPaths::HomeLocation ).join("").toUtf8() );
        }
```

**Comment by lucasm0ta** [comment]
It worked perfectly. Thanks

**Comment by itay-grudev** [comment]
Perfect. I'll patch the code.
