### ISSUE TITLE
Connection stage not changing; causing data loss

### ISSUE THREAD

**Issue by dail8859** [itay-grudev/SingleApplication#123]
I've run into a bit of an odd situation where I am missing part (first 8 bytes to be exact) of the message being sent to the primary instance.

I apologize for not having a reproducible example. I tried with the example projects in this repo without luck.

In my Windows GUI Qt 5.15.2 application, I correctly receive `SingleApplication::instanceStarted()` from which I do some Windows API magic to force the main instance to the foreground. Then I receive `SingleApplication::receivedMessage()` but the first 8 bytes of the data are missing.

I added a little debugging code into the `QLocalSocket::readyRead()` lambda to print the socket and `ConnectionInfo` stage, but it doesn't change, it always stays 0, which seems to force it to re-parse the message header and body again.

If I ignore the `instanceStarted()` signal (thus not forcing my application to the foreground), then I correctly get all data from the `receivedMessage()` signal...so I'm not sure if forcing the application to the foreground is doing some weird threading, or adding enough of a delay, or what. But something weird is happening.

Here is a snippet of the log from the primary instance of my application (with the extra debugging added to the `readyRead()` handler. The first two `0`s are the `ConnectionInfo` stage. The 3rd is showing the missing data.

![image](https://user-images.githubusercontent.com/3694843/102734867-eb3a4600-430e-11eb-9a71-6236eadac90b.png)

I am sending the string `"12345678910111213141516171819202122232425262728"` 

---

I understand the difficulty trying to guess at the problem without being able to see it yourself.

That being said, I **do** have a patch that fixes my issue. Instead of relying on the `connectionMap` to store the `ConnectionInfo` structs, I instead store them as a property of the socket object itself.

Personally I think this is much cleaner (as it stores the info directly with the object itself) and also solves the weird problem I am facing. If you are interested I can submit a patch for you to review.

**Comment by itay-grudev** [comment]
Can you create a pull request and we will take a look into your patch. If it solves the issues and makes the code more readable - brilliant!

**Comment by dail8859** [comment]
Will submit a PR when I get some time. 

I still plan on digging into it more to understand why the issue is there and have confidence the PR is the correct solution.

**Comment by dail8859** [comment]
I have been able to recreate the issue. It looks like if the `instanceStarted()` does some "processing" it can cause it to get into an invalid state.

I modified the `sending_arguments` example with the following code for `main.cpp`:

```cpp
#include <QThread>
#include <singleapplication.h>
#include "messagereceiver.h"


const SingleApplication::Options opts = SingleApplication::ExcludeAppPath | SingleApplication::ExcludeAppVersion | SingleApplication::SecondaryNotification;

int main(int argc, char *argv[])
{
    // Allow secondary instances
    SingleApplication app( argc, argv, true, opts);

    MessageReceiver msgReceiver;

    // If this is a secondary instance
    if( !app.isPrimary() ) {
        app.sendMessage("12345678910111213141516171819202122232425262728");

        qDebug() << "App already running.";
        qDebug() << "Primary instance PID: " << app.primaryPid();
        qDebug() << "Primary instance user: " << app.primaryUser();
        return 0;
    } else {
        QObject::connect(
            &app,
            &SingleApplication::receivedMessage,
            &msgReceiver,
            &MessageReceiver::receivedMessage
        );

        QObject::connect(&app, &SingleApplication::instanceStarted, []() {
            QThread::msleep(250);
        });
    }

    return app.exec();
}
```


I added some debugging to `singleapplication_p.cpp` around line 338:

```cpp
    QObject::connect(nextConnSocket, &QLocalSocket::readyRead,
        [nextConnSocket, this](){
            auto &info = connectionMap[nextConnSocket];
            qDebug() << Q_FUNC_INFO << "Enter";
            switch(info.stage){
            case StageHeader:
                readInitMessageHeader(nextConnSocket);
                break;
            case StageBody:
                readInitMessageBody(nextConnSocket);
                break;
            case StageConnected:
                Q_EMIT this->slotDataAvailable( nextConnSocket, info.instanceId );
                break;
            default:
                break;
            };
            qDebug() << Q_FUNC_INFO << "exit";
        }
    );
```

And if I run a second instance a few times this is the debug output I get:

![image](https://user-images.githubusercontent.com/3694843/102906085-225d4400-4442-11eb-8f2e-062b3246418b.png)

I'm not very familiar with threading in Qt and still plan to test my changes to see if it solves the issue and create a PR but this at least should give you something to look at as well.

**Comment by dail8859** [comment]
My code changes **will not work**. It seems to work better but still having other issues. 

I'll let someone that is more experienced in Qt IO/threading address this.

**Comment by dail8859** [comment]
Looking into it more it looks like https://github.com/itay-grudev/SingleApplication/issues/121#issuecomment-734225947 exactly describes the root cause of this issue. When the socket is disconnected, it is removed from the map, along with its connection info struct, but `readyRead()` is triggered again causing it to think it is in the initial stage of the connection.
