### ISSUE TITLE
Crash in qChecksum calculation

### ISSUE THREAD

**Issue by variar** [itay-grudev/SingleApplication#128]
Hi, I've been using SingleApplication in [klogg](https://github.com/variar/klogg) for some time now. After implementing crash dumps uploading I've received several crash reports with stack like this

```
Fatal Error: EXCEPTION_ACCESS_VIOLATION_READ
0   Qt5Core.dll                     0x7ff8572848c0      qChecksum
1   klogg.exe                       0x7ff783f96f4a      SingleApplicationPrivate::readInitMessageBody (singleapplication_p.cpp:416)
2   klogg.exe                       0x7ff783f970fa      SingleApplicationPrivate::readInitMessageHeader (singleapplication_p.cpp:373)
3   Qt5Core.dll                     0x7ff8573e5108      QObject::qt_static_metacall
4   Qt5Core.dll                     0x7ff8573e5166      QObject::qt_static_metacall
5   Qt5Core.dll                     0x7ff85737ab2b      QWindowsPipeReader::emitPendingReadyRead
6   Qt5Core.dll                     0x7ff8573ee243      QMetaCallEvent::placeMetaCall
7   Qt5Core.dll                     0x7ff8573eca50      QObject::event
8   Qt5Widgets.dll                  0x7ff857ff56ef      QApplicationPrivate::notify_helper
9   Qt5Widgets.dll                  0x7ff857ff4767      QApplication::notify
```

Looks like crash is happening  in this line
```
const quint16 actualChecksum = qChecksum(msgBytes.constData(), static_cast<quint32>(msgBytes.length() - sizeof(quint16)));
```

I've looked through code and can't see a path that may result in `msgBytes.length()` being less than `sizeof(quint16)`. And I see no other reason for access violation inside qChecksum.  I am going to add a size check before checksum calculation, but this doesn't look like proper fix for the issue as root cause is still unknown.

**Comment by jonaski** [comment]
What Qt version did you use when you encountered this?

**Comment by variar** [comment]
Crash reports come from klogg builds on Windows with Qt version 5.15.1. I don't see any crashes from more recent klogg builds which uses Qt 5.15.2. Can it be a known Qt issue?

**Comment by variar** [comment]
One of my users provided steps to reliably reproduce this issue.  Basically it happens when a lot of secondary instances are launched at once. In my case when primary instance is running and user selects many files to open in Windows Explorer, a secondary instance is being launched for each file (I don't know why Windows does that instead if passing all files to one executable). That secondary instances try to pass filename to primary process. And almost each time this crash happens.

I'll try to create minimal example.

**Comment by variar** [comment]
The issue is not reproduced with code from #133
