### ISSUE TITLE
Inconsistency?

### ISSUE THREAD

**Issue by haifenghuang** [itay-grudev/SingleApplication#131]
In the `README` file,  `Examples` section, it said:

```
Basic example that prevents a secondary instance from starting examples/basic
```
i.e. Prevents a secondary instance.

But the basic examples's main file, the code is as below:

```cpp
#include <singleapplication.h>

int main(int argc, char *argv[])
{
    // Allow secondary instances
    SingleApplication app( argc, argv );

    qWarning() << "Started a new instance";

    return app.exec();
}
```

The comment said `Allow secondary instances`. 

So I'm a little bit confused, which is correct?

**Comment by itay-grudev** [comment]
@haifenghuang That comment shouldn't be there. The `// Allow secondary instances` is the third argument to the constructor and defaults to `false`. As you can see it's not passed here.
