### ISSUE TITLE
#133 causes a breaking change of the return value of `SingleApplication::sendMessage` on timeout

### ISSUE THREAD

**Issue by ouuan** [itay-grudev/SingleApplication#135]
Before #133, `SingleApplication::sendMessage` didn't return `false` when it timeouts. Now it does. So #133 is a breaking change, which does break at cpeditor/cpeditor#853.

I think it should be documented, or we should provide a new function/parameter for the new behavior.

**Comment by itay-grudev** [comment]
Very well. We'll do that.
