### ISSUE TITLE
AppImages not working

### ISSUE THREAD

**Issue by ahrm** [itay-grudev/SingleApplication#137]
I have essentially the same issue as https://github.com/itay-grudev/SingleApplication/issues/77 which is marked as closed so I opened a new one.

The problem is `isSecondary` returns false even for the second instance of the application. (this error only occurs when the app is packaged using appimage and not in the original binary as shown in the video below).

https://user-images.githubusercontent.com/6392321/128221709-c81fe412-da00-4e99-b6d6-cdfaab37d793.mp4

Here is the source code for the example:
```
#include <iostream>
#include <qapplication.h>
#include <qpushbutton.h>
#include <singleapplication.h>

int main(int argc, char** args){
  SingleApplication app(argc, args, true);
  if (app.isSecondary()){
    std::cout << "I am secondary,\n";
    return 0;
  }
  else{
    std::cout << "I am primary.\n";
  }
  QPushButton button("Click Me!");
  button.show();
  app.exec();

  return 0;
}
```

and this is the .pro file:

```
TARGET = app

QT += core gui widgets

SOURCES += main.cpp

include(SingleApplication/singleapplication.pri)
DEFINES += QAPPLICATION_CLASS=QApplication

isEmpty(PREFIX){
  PREFIX = /usr
}
target.path = $$PREFIX/bin
shortcutfiles.files = resources/app.desktop
shortcutfiles.path = $$PREFIX/share/applications/
data.files = resources/icon.png
data.path = $$PREFIX/share/pixmaps/
INSTALLS += shortcutfiles
INSTALLS += target
INSTALLS += data
DISTFILES += resources/app.desktop\
    resources/icon.png

```
and this the build script. I use linuxdeploy with the qt plugin:
```
qmake build.pro
make install INSTALL_ROOT=approot

./linuxdeploy.AppImage --appdir approot --plugin qt --output appimage
```

I am using Qt 5.12.4 on Ubuntu 21.04 .

**Comment by mklein-de** [comment]
You need to add the `Mode::ExcludeAppPath` flag like this:

```C++
SingleApplication app(argc, args, true,
    SingleApplication::Mode::User | SingleApplication::Mode::ExcludeAppPath);
```

Each AppImage has its own mount point, so the path to the executable obviously differs and must not go into the shared memory key.

**Comment by itay-grudev** [comment]
That's a very good point. I will mark the issue as closed. Ping me if you still have issues @ahrm.
