### ISSUE TITLE
Latest commit caused app crashed constantly

### ISSUE THREAD

**Issue by csuft** [itay-grudev/SingleApplication#138]
Hi, the latest commit crashes my app constantly. Yesterday I update single application from commit fda9c4(April 29) to d5b385(Aug 4) and my app just keeps crashing. The stacktrace looks like the following:

<img width="708" alt="2021-08-19_102452" src="https://user-images.githubusercontent.com/3948137/129998668-ff471e92-5825-4f47-abad-6a4703c8737b.png">

I compiled my project on Windows 10 with Visual Studio 2017, nothing else changed but this library.

**Comment by itay-grudev** [comment]
I apologise for the late response. Are you using `master` or one of the stable releases?
