### ISSUE TITLE
Signal Custom handling

### ISSUE THREAD

**Issue by purell** [itay-grudev/SingleApplication#15]
Hi

It could be great if we can override/intercept the signals (SIGHUP , SIGINT, etc...). As our application could clean its resources and then next call a SingleApplication crash handler. Ex : 

``` c++
#include <QApplication>
#include <SingleApplication.h>

void myApplicationCrashHandler(int sig) {

    // Doing custom Qt Application clean-up....
    // ...
    // ...

    // Calling the SingleApplication normal crash handler
    SingleApplication::signalCrash(sig);
}

int main( int argc, char* argv[] )
{
    SingleApplication app( argc, argv );

    // Install a custom crash handler
    SingleApplication::installCrashHandler( &myApplicationCrashHandler );

    return app.exec();
}
```

Maybe this is already possible, but I have not found how. Because without the mechanism we cannot kill/free resources properly of our application.

**Comment by itay-grudev** [comment]
Good Point. You don't happen to be interested in implementing something like that, are you?

**Comment by itay-grudev** [comment]
I like the idea, though I won't have time to implement it soon, though it is rather trivial to implement.

**Comment by purell** [comment]
I could and I will but now our class is the only one suitable for my need except for this point. But I'm not sure how I will introduce it yet. I will work on it tomorrow or next week and come back with a pull request ASAP.

By the way, thank you very much for sharing your work.

**Comment by itay-grudev** [comment]
Perfect. Thank you!

The implementation could be in the form of a boolean flag to disable the default signal handling and apply a custom one. The crash handler could be a separated public (static) method. This would also allow for the scenario where you might have different handlers for different signals. It's going to be a bit more flexible I think.

Regarding sharing my work... I personally benefit so much from the Open Source community that it's only fair if I share some my work in return.

**Comment by itay-grudev** [comment]
This was fixed some time ago. SingleApplication no longer intercepts signals.
