### ISSUE TITLE
Recording video has stuttering effect

### ISSUE THREAD

**Issue by lion-no-back** [itay-grudev/SingleApplication#162]
I like this product very much. I have used it for a month. When I used it yesterday and today, I found that the video recording was a little stuck. Can this part be optimized? Thank you very much for making this product open source, it has benefited many people like me who need such a tool

**Comment by Shatur** [comment]
Wrong repo?

**Comment by lion-no-back** [comment]
Sorry, I borrowed your open source project for one of my products, clicked in and didn't look at it, and it was the wrong repository.
