### ISSUE TITLE
The new license might no longer be GPL-compatible

### ISSUE THREAD

**Issue by q234rty** [itay-grudev/SingleApplication#171]
First of all, I'm not a lawyer so the below should be taken with a grain of salt and should not be taken as professional advice.

There are two issues with the current license:
Firstly, Microsoft claims that their usage of code published on GitHub as training data is under fair use. If that statement holds legally, then no amount of licensing change can illegalize their usage. If that statement does not hold legally, then they are already violating most software licenses.
Secondly and more importantly, as far as I understand the GPL, the new license might no longer be GPL-compatible i.e. projects under the GPL might no longer be able to use this project.

One suggestion would be protest the use as training data in the copyright notice, but leave the conditions of the MIT license unchanged. 

Another suggestion would be make the project available as the new license OR another compatible license, but I personally does not like that as that makes the licensing situation unnecessarily complicated for a small project.

**Comment by itay-grudev** [comment]
I suppose the usage of our software can be roughly divided in two scenarios:

1. Your software project does not include the SingleApplication code
    In this case either it's included as a git submodule, or added in compile time by CMake and 
    friends. In this case there is no issue in complying to the license and distributing your 
    software as is, as when your project gets stolen as training data, it would not include ours.
2. Your software includes the SingleApplication code
    In this scenario you have some sort of sub-directory that contains our software and if your
    projects gets ingested as training data, it would violate our license.
    
The MIT License requires that the our `LICENSE` note is available in your software no matter the use. To make it clear our advice in scenario 2  would be to make sure our `LICENSE` file is in the directory where the SingleApplication code is located (usually the case) and continue to freely enjoy the other freedoms granted by it.

Our license does not prevent you from distributing your software, building or linking it either statically or dynamically in both commercial and non-commercial projects and/or OSS software including GPL licensed one.

The only thing we disagree with is the unfair usage of the source as machine learning training data, which results in no attribution to the author, not compensation for their time and and efforts, effectively breaking even the MIT license. We just wanted to make that explicit.

And if you really want to make it clear, you can put a note somewhere in your project that says:

> Certain parts of this project cannot be used as sample data for the purposes of building machine learning models. Refer to the respective `LICENSE` file on the corresponding directories.

**Comment by q234rty** [comment]
As far as I understand, the GPL requires that when combining software licensed under the GPL and software licensed under another license, the combined software must be licensed under the GPL with possibly some addtional terms as specified in section 7 of the [GPLv3](https://www.gnu.org/licenses/gpl-3.0.html) . I do not think that is possible with the new license since it is in theory possible to have a machine learning model that does respect the licenses.

> The only thing we disagree with is the unfair usage of the source as machine learning training data, which results in no attribution to the author, not compensation for their time and and efforts, effectively breaking even the MIT license. We just wanted to make that explicit.

I believe you can include that as a part of the copyright notice instead of the conditions of the license.

**Comment by itay-grudev** [comment]
The way I see it, you should treat SingleApplication as a separate work in your GPL licensed project and make sure our Copyright Notes and especially their machine learning restriction are there to be found, as required by our License.

You should distributed our project in a separate directory with its own copyright notice and ensure it is clear that it is a separate work.

Our License grants you plenty of freedom otherwise. I strongly believe in its intention and I am very reluctant to changing it.

**Comment by q234rty** [comment]
> The way I see it, you should treat SingleApplication as a separate work in your GPL licensed project and make sure our Copyright Notes and especially their machine learning restriction are there to be found, as required by our License.

The thing is singleapplication would be a part of the binary, so by GPL definitions one can not really say it's completely seperate work.

> I strongly believe in its intention

I agree that it's well intentioned and I share your dismay about Copilot, ChatGPT etc., but what it actually does is:

1. Does nothing to Microsoft since they believe their usage is "fair use" regardless of license. If their usage does not falls into "fair use", they are already violating the licenses anyway.
2. Makes using the project hard.

**Comment by itay-grudev** [comment]
I understand your point and will research it.

**Comment by q234rty** [comment]
Yeah, if you just want to voice your dismay on AI in your license it's fine and there's a lot of ways to do that while keeping the license GPL-compatible, but changing the license does not prevent Microsoft from using your code as data since they are currently disregarding all licenses in the name of "fair use". If licenses were respected then the GPL itself would have worked and there would be no need to create a new license. In general it's usually not a good idea to make up your own license.

**Comment by hosiet** [comment]
Thank you for the discussion. I noticed this license change when preparing maintenance to packaged version of SingleApplication in Debian ( https://tracker.debian.org/pkg/singleapplication ). Looks like the license forbids utilization of software (which would be interpreted to both source code and compiled outcomes) on machine learning, and this violates Debian's DFSG guideline No.6 (at https://www.debian.org/social_contract.en.html ). This analysis is not related to GPL compatibility.

Given such concern, I will keep Debian's packaged version before the license change. I will continue to monitor this case.

**Comment by suy** [comment]
> this violates Debian's DFSG guideline No.6 (at https://www.debian.org/social_contract.en.html ). This analysis is not related to GPL compatibility

IANAL either, but if it's not DFSG-compatible, since the DFSG definition is more or less the same definition of the OSI one, it means the software is not likely at all to be OSI approved or comply with the definition of Free Software from the FSF either. :-(

This is very problematic for many of us. IMHO, not only it's GPL-incompatible, it's also just not Free Software/Open Source.

Note that, additionally, it is very likely (again, not a lawyer) that the clause is useless in achieving much, but stirring a conversation in between us. Some countries seem to have explicitly said that it is legal to train an AI:

https://storialaw.jp/en/service/bigdata/bigdata-12

> which allows the use of copyrighted products to a certain extent without the
> copyright holder’s consent if such use is for the purpose of developing AI.

https://felixreda.eu/2021/07/github-copilot-is-not-infringing-your-copyright/

> Under the slogan “The Right to Read is the Right to Mine”, EU-based research
> associations therefore demanded explicit permission in European copyright law
> for so-called text & data mining, that is the permanent storage of copyrighted
> works for the purpose of automated analysis. The campaign was successful, to
> the chagrin of academic publishers. Since the EU Copyright Directive of 2019,
> text & data mining is permitted.

I share your concern, though, and I indeed have seen CoPilot outputting copyrighted code under entirely wrong terms. But in that case, I'm afraid the better strategy would be to move to a different hosting.

**Comment by itay-grudev** [comment]
@suy I just consulted with a copyright lawyer about the article you shared. Quite an interesting read, thankfully it's mostly wrong and the assumptions made there would not stand in court, according to her. Of course it hasn't been tested so far - can't wait.

**Comment by itay-grudev** [comment]
In the mean time - I genuinely apologize for the situation I love free software but it's being abused in a way I don't like. So - the license stays.

**Comment by suy** [comment]
Thank you for your consideration, @itay-grudev. I hope we can have a fully definitive answer soon, if this gets tested in court. Cheers.
