### ISSUE TITLE
Restart application failed

### ISSUE THREAD

**Issue by L-Super** [itay-grudev/SingleApplication#175]
I need restart application sometimes, but SingleApplication will make it restart failed.

```cpp
        QTimer::singleShot(500, this, []{
            qApp->quit();
            auto app = qApp->applicationFilePath();
            QProcess::startDetached(app, QStringList());
        });
```

When I launch application on terminal, it shows log:
```
QWindowsPipeWriter: asynchronous write failed. (管道已结束。)
```

Platform: Windows 11 Qt 5.15.2

**Comment by itay-grudev** [comment]
You're raising a ticket in the wrong repository. You're referring to QtSingleApplication, which has a lot of issues.

This project is a replacement and it's API and implementation is significantly different.

**Comment by itay-grudev** [comment]
Refer to our documentation here for our API if you want to give our project a try:

https://itay-grudev.github.io/SingleApplication/

**Comment by L-Super** [comment]
> You're raising a ticket in the wrong repository. You're referring to `QtSingleApplication`, which has a lot of issues, indeed.
> 
> This project is a replacement of `QtSingleApplication` and it's API and implementation are significantly different.

No, you are wrong. I'm using your repository.

![image](https://github.com/itay-grudev/SingleApplication/assets/40905056/c4724a68-f663-41c3-9dda-37ba358373dc)

**Comment by itay-grudev** [comment]
I think the problem may be the following:

When you call the `quit()` slot, it indicated that the application should be shutdown when the event-loop is finished. But that doesn't happen or by the time the new application starts the old one hasn't shut down yet.

If this is correct, at the time the new instance starts there is already a primary instance and depending on your settings it would probably just shut down.

**Comment by itay-grudev** [comment]
I don't think we support such a use case cleanly. I can think of several ways of solving it.

1. Exec into the new application, completely replacing the original process. This should invalidate the original primary instance.
2. Add an artificial wait before the SingleApplication constructor, so the old primary instance has time to shut down.
3. Create PR that modifies the library and allows demoting a primary instance to secondary, such that the next instance started would become the primary.
