### ISSUE TITLE
key too long on macos

### ISSUE THREAD

**Issue by flaviotordini** [itay-grudev/SingleApplication#178]
With Qt 6.6.0 on macOS version 12.3.1 Intel I get this error on startup:

```
[SingleApplication::SingleApplication] SingleApplication: Unable to create block.
[SingleApplication::abortSafely] SingleApplication:  QSharedMemory::KeyError "QSharedMemoryPrivate::initKey: unable to set key on lock (QSystemSemaphore::handle: key too long)"
```

**Comment by flaviotordini** [comment]
I don't know the details, but in general shouldn't this lib allow a second instance rather than completely failing?

**Comment by itay-grudev** [comment]
Just to clarify, which version of the kl library are you using?

**Comment by flaviotordini** [comment]
Ah sorry, the latest version: 3.5.0

**Comment by itay-grudev** [comment]
@jonaski Can you help me with this one, as this is likely related to #177?

**Comment by jonaski** [comment]
It's using shm_open(), this is not a problem on Linux and other unix variant because it uses PATH_MAX, but on macOS the maximum key length is PSHMNAMLEN (31). While the base64 encoded cryptographic hash we use is 44.
I tested the old constructor taking QString instead of QNativeIpcKey, and it's as broken as on Linux (as I explained in the issue), so switching back is not an alternative.
The only simple fix I see now is to use a base64 encoded string instead of the cryptographic hash for macOS.

**Comment by jonaski** [comment]
Unfortunately there seem to be a another issue on macOS too, once the application is started and  you quit normally, you still can't start it again, so the memory is not released, Qt bug perhaps.

**Comment by itay-grudev** [comment]
Does that mean that even with the fix in #180 it won't work?

**Comment by jonaski** [comment]
It solves the issue related to the key size, so the application starts, but there are still issues since the shared memory isn't released.

**Comment by itay-grudev** [comment]
@jonaski I documented it as a known issue in the [release notes](https://github.com/itay-grudev/SingleApplication/releases/tag/v3.5.1).

> 
> **Known issues:**
> 
> Using Qt 6.6+ on macOS once the application is started and you quit normally, you still can't start it again. This is likely due to a Qt bug. We are still looking for a workaround.

**Comment by jonaski** [comment]
If someone with a mac has a chance to dig into this more, there is a small test project attached to the Qt bug report on https://bugreports.qt.io/browse/QTBUG-111855
