### ISSUE TITLE
QGuiApplication not work

### ISSUE THREAD

**Issue by uralbash** [itay-grudev/SingleApplication#18]
I'm trying to use singleapp with ``QGuiApplication`` as base class.

```cpp
#ifndef QAPPLICATION_CLASS
  #define QAPPLICATION_CLASS QGuiApplication
#endif

#include "singleapplication.h"

int main(int argc, char *argv[])
{
    // QGuiApplication app(argc, argv);  --> Work
    SingleApplication app(argc, argv);
```

but everytime get error:

```
Cannot create window: no screens available
```

**Comment by itay-grudev** [comment]
Make sure you really are using `QGuiApplication`. Explicitly define it without the conditional statement:

```cpp
#define QAPPLICATION_CLASS QGuiApplication
```

**Comment by uralbash** [comment]
Yes, I tried to use this way too and check class with ``qDebug() << QT_STRINGIFY(QAPPLICATION_CLASS)`` in main function but get same error.

**Comment by itay-grudev** [comment]
Does `QApplication` work?

**Comment by itay-grudev** [comment]
Because the calculator example uses `QWidget`s with `QApplication` and it works fine.

**Comment by uralbash** [comment]
I checked with ``QApplication`` it's works directly but not with QAPPLICATION_CLASS.
Perhaps the problem exists only with ``Qml``, here is my full code:

```cpp
#include <QtQml/QQmlContext>
#include <QtGui/QGuiApplication>
#include <QtQml/QQmlApplicationEngine>
#include <QtWebEngine/qtwebengineglobal.h>

#ifndef QAPPLICATION_CLASS
  #define QAPPLICATION_CLASS QApplication
#endif

#include "singleapplication.h"

int main(int argc, char *argv[])
{
    qDebug() << QT_STRINGIFY(QAPPLICATION_CLASS); // QApplication output
//    SingleApplication app(argc, argv); --> Error: Cannot create window: no screens available
//    QGuiApplication app(argc, argv);   --> Work
    QApplication app(argc, argv);  //    --> Work

    // WebEngine
    QtWebEngine::initialize();

    // QML engine
    QQmlApplicationEngine engine;

    // Load QML application
    engine.load(QUrl(QStringLiteral("qrc:/main.qml")));

    return app.exec();
}
```

**Comment by itay-grudev** [comment]
I really doubt this is a SingleApplication problem. This is a very basic functionality that couldn't possibly fail. I believe the problem is somewhere in your environment.

**Comment by liulex** [comment]
@uralbash 

Are you using Visual Studio?

Instead of using
```C++
#define QAPPLICATION_CLASS QApplication
```
try adding `QAPPLICATION_CLASS=QApplication` to

"`Project Property Pages` - `Configuration properties` - `C/C++` - `Preprocessor` - `Preprocessor Definitions`".

I had the same problem when working with Visual Studio and this method should solve it.

**Comment by uralbash** [comment]
@liulex I'm use QtCreator I try to avoid it through ``DEFINES += "QAPPLICATION_CLASS=QGuiApplication"`` but it doesn't help. You can try do it with ``quicknanobrowser`` example, it doesn't work too for me.

```cpp

#include "utils.h"

#ifndef QT_NO_WIDGETS
#include <QtWidgets/QApplication>
typedef QApplication Application;
#else
#include <QtGui/QGuiApplication>
typedef QGuiApplication Application;
#endif
#include <QtQml/QQmlApplicationEngine>
#include <QtQml/QQmlContext>
#include <QtWebEngine/qtwebengineglobal.h>

#ifndef QAPPLICATION_CLASS
  #define QAPPLICATION_CLASS QApplication
#endif

#include "singleapplication.h"


static QUrl startupUrl()
{
    QUrl ret;
    QStringList args(qApp->arguments());
    args.takeFirst();
    Q_FOREACH (const QString& arg, args) {
        if (arg.startsWith(QLatin1Char('-')))
             continue;
        ret = Utils::fromUserInput(arg);
        if (ret.isValid())
            return ret;
    }
    return QUrl(QStringLiteral("http://qt.io/"));
}

int main(int argc, char **argv)
{
    SingleApplication app(argc, argv);

    QtWebEngine::initialize();

    QQmlApplicationEngine appEngine;
    Utils utils;
    appEngine.rootContext()->setContextProperty("utils", &utils);
    appEngine.load(QUrl("qrc:/ApplicationRoot.qml"));
    QMetaObject::invokeMethod(appEngine.rootObjects().first(), "load", Q_ARG(QVariant, startupUrl()));

    return app.exec();
}

```

**Comment by liulex** [comment]
@uralbash 
If you don't want to define it globally, I think you would need to find a way to ensure `main.cpp` is compiled before `singleapplication.cpp`.

**Comment by itay-grudev** [comment]
@liulex Is correct. Alternatively can overwrite the definition in the singleapplication.h directly.

**Comment by uralbash** [comment]
@liulex @itay-grudev Yes, you are right I solve problem after rebuild project with defines:
``DEFINES += QAPPLICATION_CLASS=QGuiApplication``
