### ISSUE TITLE
args_for_main.join( ) puts a separator on every space

### ISSUE THREAD

**Issue by quimup** [itay-grudev/SingleApplication#187]
Good evening,

The 'sending_arguments' example code has this line:

`app.sendMessage( app.arguments().join(' ').toUtf8() );`

In my hands 'join' replaces every space with a separator.
Arguments like filenames, with spaces in it, are consequently broken up and cannot be restored with 'split'.

Example: Using ** as separator, the single argument `David Bowie Heroes.mp3` ends up in the message as `David**Bowie**Heroes.mp3` which after 'split' gives me 3 arguments:  `David', 'Bowie' and 'Heroes.mp3'

Am I overlooking something, or is this a bug?

Best wishes for 2024,

Johan Spee

**Comment by itay-grudev** [comment]
It seems like your argument is interpreted as 3 arguments because of the spaced. Consider escaping it like:

```console
./yourprogram David\ Bowie\ Heroes.mp3
./yourprogram 'David Bowie Heroes.mp3'
./yourprogram "David Bowie Heroes.mp3"
```

**Comment by quimup** [comment]
There is nothing for me to escape. The arguments arrive via 'open with' (%U). I worked around it by putting the separate arguments in a QStringList (`myarguments`) myself and send that in stead of `app.arguments()`:
`app.sendMessage( myarguments().join(' ').toUtf8() );`
and that works like expected.
The problem, therefore, must be `app.arguments()` wich does not contain separate arguments, but anything sparated by a space.

**Comment by itay-grudev** [comment]
I think this is coming from a misunderstanding of how CLI arguments are treated. If you do have a better solution, feel free to open a PR.
