### ISSUE TITLE
Consider making SingleApplication as a hook

### ISSUE THREAD

**Issue by SineStriker** [itay-grudev/SingleApplication#188]
If my application needs to derive `QApplication`, then migrating to `SingleApplication` would have to change to derive from `SingleApplication`, which would be too intrusive to user code.

Consider the following workaround, we create a `QApplication` first and then create `SingleApplication`. The `SingleApplication` instance can initialize it self and install hooks on `qApp` in its constructor.

We also don't need to set up the base class in CMake.

```c++
int main(int argc, char *argv[]) {
    QApplication a(argc, argv);
    SingleApplicationHook single;

    QWindow window;
    window.show();

    QObject::connect(
        &single,
        &SingleApplication::instanceStarted,
        &window,
        &QWindow::raise
    );
    return a.exec();
}
```
In many scenario, using "combination" rather than "inheritance" is more user-friendly.

**Comment by itay-grudev** [comment]
@SineStriker It shouldn't be intrusive as `SingleApplication` can derive from any `QApplicationCore` compatible class such as `QApplication` or `QGuiApplication`. It only extends those classes and thus should not be disruptive.
