### ISSUE TITLE
A liitle confused about Mode::SecondaryNotification

### ISSUE THREAD

**Issue by mokugyos** [itay-grudev/SingleApplication#193]
What does this flag mean? I set:
SingleApplication app(argc, argv, false, SingleApplication::System | SingleApplication::SecondaryNotification);
SingleApplication app(argc, argv, false, SingleApplication::System);

In both cases, void instanceStarted() can be triggered.

Thanks.

**Comment by itay-grudev** [comment]
It's intended for the `SingleApplication app(argc, argv, `**true**`, SingleApplication::System | SingleApplication::SecondaryNotification)` case.

By default it wouldn't trigger for a secondary instance start.
You can check the full documentation [here](https://itay-grudev.github.io/SingleApplication/classSingleApplication.html#af627160aff1baf822780f3232e43cc3f)
