### ISSUE TITLE
Your project is building and running fine on Qt 4.8.1 too! Thank you.

### ISSUE THREAD

**Issue by PavelDorofeev** [itay-grudev/SingleApplication#195]
Hello! Your project is building and running fine on Qt4.8.1 too! Thank you.

**Comment by itay-grudev** [comment]
Did you also had to support Windows XP for some reason?

**Comment by PavelDorofeev** [comment]
> Did you also have to support Windows XP for some reason?

It is my old history with Qt4. I prepared IDE and building Qt (and my applications) from sources (staticly and shared) and developing my branch of Qt4. It is more convenient for me.
