### ISSUE TITLE
Does not work with Flatpak

### ISSUE THREAD

**Issue by beedaddy** [itay-grudev/SingleApplication#199]
Installing/running the application from Flatpak allows opening multiple instances. This seems to bypass SingleApplication's mechanism or am I overlooking something?

**Comment by itay-grudev** [comment]
You may need to add: `--device=shm` for shared memory access, which the library uses for inter-process communication. Without that every instance will be convinces it's the primary instance.

**Comment by beedaddy** [comment]
Thanks a lot, @itay-grudev. `--device=shm` works. I knew I missed something.

**Comment by beedaddy** [comment]
> Dumb question...where does that --device flag go? Is it when launching the app via command line? Or is that part of the flatpak app config?

It is part of the flatpak app config (.yml) file. In my case, the relevant part looks like this:
```
[…]
finish-args:
  # X11 + XShm access
  - --share=ipc
  - --socket=fallback-x11
  # Wayland access
  - --socket=wayland
  # Needs to talk to the network:
  #- --share=network
  # Needs to save files locally
  - --filesystem=host
  # Needed for SingleApplication:
  - --device=shm
[…]
```
