### ISSUE TITLE
QLocalSocket is not released

### ISSUE THREAD

**Issue by kklimek** [itay-grudev/SingleApplication#2]
Hi, I've read your code and noticed that you never delete QLocalSocket returned from "nextPendingConnection" .

https://github.com/itay-grudev/SingleApplication/blob/master/singleapplication.cpp#L45

Best solution I gues would be connecting returned socked signal disconnected() to deleteLater() slot. Also you're creating server without parent so it won't be deleted

**Comment by itay-grudev** [comment]
I just checked. You are correct, it is a pointer and it has to be deleted. Thanks.

**Comment by itay-grudev** [comment]
How abut just manually disconnect it. It is not required anyway. I think this should do...

```
QLocalSocket *socket = server->nextPendingConnection();
socket->close();
delete socket;
emit showUp();
```

**Comment by kklimek** [comment]
Well it will work of course, I've sugested the way with disconnected, as the other side will close so it will disconnect.

**Comment by kklimek** [comment]
not best way, but will do the work

**Comment by itay-grudev** [comment]
By explicitly disconnecting the socket from the server ensures that the memory will be deleted right away and wouldn't require any additional entries to the Qt's event system. Though in this case the client disconnect is no longer required.. Will fix it.

**Comment by kklimek** [comment]
as far as I know close for sockets is not sync operation. So calling "delete" will probably sync disconnection anyway and will produce "additional entries to the Qt's event system"
