### ISSUE TITLE
Better UserName

### ISSUE THREAD

**Issue by hojjatjafary** [itay-grudev/SingleApplication#22]
Hi, 
Thanks for sharing the code,
you used` QStandardPaths::standardLocations( QStandardPaths::HomeLocation )` for getting user info but Qt will use `HOMEPATH `environment variable on Windows that is not very reliable because it can be changed by user.
A better way is to use Win Api [GetUserName ](https://msdn.microsoft.com/en-gb/library/windows/desktop/ms724432(v=vs.85).aspx)or [GetUserNameEx](https://msdn.microsoft.com/en-us/library/ms724435(v=VS.85).aspx).

GL,
Hojjat.

**Comment by hojjatjafary** [comment]
heh you removed that in 3.0.3a

**Comment by itay-grudev** [comment]
Funny right. I agree with you, but I had multiple issues reported with GetUserName and decided to remove it. An additional factor is that I don't have a Windows machine at the moment so I can't make a rigorous testing with multiple compilers and etc.

If you would like to volunteer, I'd gladly include the code back.

P.S. See issue #19. I can't test whether it's only on that compiler. And I don't know what will happen if I include this in the `.pri` file:

```qmake
win32 {
    LIBS += Advapi32.lib
}
```

Would it work for all Ms platforms and compilers or if it's a Qt 5.7.1 32 bit MSVC 2015 specific problem.

**Comment by itay-grudev** [comment]
@char101

**Comment by char101** [comment]
`HOMEDRIVE` is used only as a fallback, see 

https://code.woboq.org/qt5/qtbase/src/corelib/io/qfilesystemengine_win.cpp.html#1162

If you want to be really really sure I guess you can combine the user home with `QStandardPaths::AppDataLocation`. I don't think `AppDataLocation` is overrideable in Windows.

**Comment by itay-grudev** [comment]
I was just thinking about the same thing, but I wasn't sure whether AppDataLocation isn't just `$HOMEPATH/AppData/...`

**Comment by itay-grudev** [comment]
Also we shouldn't solely relay on the Qt source code as it can change. The best solution is with the Windows API but as I said I have no way of testing it at the moment.

**Comment by hojjatjafary** [comment]
I can test it with Qt Creator VS2015, this type of link errors are not so hard to resolve.

**Comment by itay-grudev** [comment]
Great. When I have time during the weekend I'll send you a zip with the modified source. It will be great if you test it with VS2015. Other compilers may also be useful.

Could you email me on: itay+SAissue-22-github.com@grudev.com so I have your emails and I'll send you a version of the library to test. I may also add in some qDebug statements to save you time.

If everything is OK, I'll publish a new version with the GetUserName api.

Thanks a lot guys!

**Comment by itay-grudev** [comment]
Could you guys try this out?
https://github.com/itay-grudev/SingleApplication/tree/username_windows

**Comment by hojjatjafary** [comment]
I've tested the project on Windows7 and Visual Studio2015,
seems you should change `singleapplication.pri` this way :
```
win32 {
    LIBS += -lAdvapi32
}
```

instead of writing lib's complete name.

**Comment by itay-grudev** [comment]
I assume it works now. @char101 Can you too verify that this works correctly in your environment?

**Comment by itay-grudev** [comment]
Gentlemen, there is also a `qDebug()` statement printing the username to STDIN. Possibly with a new line, but that's not important. Could you verify that it's correct, please.

**Comment by hojjatjafary** [comment]
The printed username is OK, but the lib should be fixed.

**Comment by itay-grudev** [comment]
It is fixed on the username_windows branch.

https://github.com/itay-grudev/SingleApplication/commit/a6b50c91f4e55b21b2b79381b24c04babec54c46

**Comment by hojjatjafary** [comment]
Nice, thanks.

**Comment by char101** [comment]
@hojjatjafary 

Why are you using gcc syntax on Visual Studio?

See the example on qmake documentation

```
unix:LIBS += -L/usr/local/lib -lmath
win32:LIBS += c:/mylibs/math.lib
```

**Comment by char101** [comment]
Maybe better (handles both msvc and mingw on win32):

```
win32 {
    msvc:LIBS += Advapi32.lib
    gcc:LIBS += -lAdvapi32
}
```

Note: I can't test this configuration now.

**Comment by char101** [comment]
@itay-grudev An alternative is to bind the `GetUserName` function at runtime like Qt does, that way you don't have to change the linker flags.

**Comment by itay-grudev** [comment]
@char101 What exactly are you referring to? Can you give me an example?

**Comment by itay-grudev** [comment]
P.S. the username_windows branch now contains your compiler specific implementation.

**Comment by itay-grudev** [comment]
I pushed the changes onto `master`. Thanks guys!

**Comment by hojjatjafary** [comment]
@char101 
it is not gcc syntax, it is qmake syntax!, according to the qmake documentation it will be handled on windows:
>  You can use the Unix -l (library) and -L (library path) flags and **qmake will do the correct thing with these libraries on Windows** and the Symbian platform 

the only note is the library versions.
I've not tested this new configuration yet but it is good if it works.

**Comment by itay-grudev** [comment]
I am much more comfortable with Qt handling the flags than hardcoding them. Thanks @hojjatjafary. I'll fix it when I have time.

**Comment by char101** [comment]
Okay, I have tested compiling it with `-lAdvapi32` and it compiles with Visual Studio 2015.

By the way @itay-grudev one thing I have just thought is that `Advapi32.lib` requires Windows SDK installation and it's a big installation. AFAIK compiling Qt on Windows does not require the Windows SDK, so it could be one thing to consider to load the `GetUserName` function at runtime instead of linking it at compile time.

**Comment by char101** [comment]
Something like

```C++
typedef BOOL (WINAPI *PtrGetUserNameW)(LPTSTR, LPDWORD);
static PtrGetUserNameW ptrUserNameW = 0;

HINSTANCE advapiHnd = QSystemLibrary::load(L"advapi32");

ptrGetUserNameW = (PtrGetUserNameW)GetProcAddress(advapiHnd, "GetUserNameW");

ptrGetUserNameW(username, &usernameLength);
```

**Comment by itay-grudev** [comment]
Would any of you guys like to implement that?

**Comment by itay-grudev** [comment]
Perfect. Can you make a PR with a working version and I'll merge it. I just don't have a Windows machine to play around with it, at the moment.

**Comment by char101** [comment]
@itay-grudev PR sent.

**Comment by hojjatjafary** [comment]
Thank you @char101.
