### ISSUE TITLE
Multiple instances of SingleApplication?

### ISSUE THREAD

**Issue by retmas** [itay-grudev/SingleApplication#24]
All stuff dealing with sharedMem object is completely needless and even potentially dangerous.
Why? Lets review some parts of code.
```C++
    QList<SingleApplicationPrivate*> SingleApplicationPrivate::sharedMem;
    QMutex SingleApplicationPrivate::sharedMemMutex;
// ...
        // This guarantees the program will work even with multiple
        // instances of SingleApplication in different threads.
        // Which in my opinion is idiotic, but lets handle that too.
        {
            sharedMemMutex.lock();
            sharedMem.append( this );
            sharedMemMutex.unlock();
        }
```
In fact, there can't be any guarantees whether program will work or not if there are multiple instances of SingleApplication. As mentioned in [Qt documentation](http://doc.qt.io/qt-5/qapplication.html#details)

> For any GUI application using Qt, there is precisely one QApplication object, no matter whether the application has 0, 1, 2 or more windows at any given time.

and this rule is applied to QGuiApplication and QCoreApplication as well.
Moreover, from [here](http://doc.qt.io/qt-5/qsharedmemory.html#details)

> HP-UX: Only one attach to a shared memory segment is allowed per process. This means that QSharedMemory should not be used across multiple threads in the same process in HP-UX

That means you cant even properly create multiple instances of SingleApplication on systems like HP-UX.

Besides that, SingleApplicationPrivate::terminate signal handler is buggy (review man 7 signal in section Async-signal-safe functions), and use of signal() to set a signal's disposition to a function is not portable.
In general, setting signal handlers by library is not a good decision

**Comment by itay-grudev** [comment]
What you said about the thread safe behaviour does make sense. I'll remove it.

The terminate handler is important because if you have a primary and secondary instance running, if the primary instance is shut down while the secondary is running the shared memory block will remain. Thus any attempt to create a new primary instance is going to fail. Upon shutting down, the primary instance needs to do some clean up and mark itself as shut down in the shared memory.

In #15 it was proposed that I allow for some custom signal handling on top of the one that is required by the library.

**Comment by itay-grudev** [comment]
If you have a good proposal for a better method for handling this – I'll listen.

**Comment by retmas** [comment]
> The terminate handler is important because if you have a primary and secondary instance running, if the primary instance is shut down while the secondary is running the shared memory block will remain.

What do you mean by saying secondary?
Secondary instance in the same process? If so, due to said above, we don't need it. And we shall not have any secondary,
Secondary instance that running in another process? If so..., is SingleApplication a kind of sigleton (by mean of name and logic)?
Nevertheless, any attempt to create a new primary instance is _not_ going to fail. Because before creating it does:
```
    // Guarantee thread safe behaviour with a shared memory block. Also by
    // explicitly attaching it and then deleting it we make sure that the
    // memory is deleted even if the process had crashed on Unix.
#ifdef Q_OS_UNIX
    d->memory = new QSharedMemory( d->blockServerName );
    d->memory->attach();
    delete d->memory;
#endif
```
In fact, that is what crashHandler() should do (instead of error-prone setting signal handlers and ill formed terminate() function):
```
#ifdef Q_OS_UNIX
void SingleApplicationPrivate::crashHandler()
{
    QSharedMemory cleanupEnsureObject(d->blockServerName);
    // tries to attach to shared mem system object (if any remaining,
    // even remaining after crash)
    cleanupEnsureObject.attach();
    // If previously attached, normally detaches from shared memory object
    // on cleanupEnsureObject destruction. Shared memory object is deleted
    // from the system as the last attached process detaches from it.
    // In that case a new, distinct object can be created
}
...
SingleApplication::SingleApplication(...)
{
...
#ifdef Q_OS_UNIX
    crashHandler();
#endif
...
    // Create a shared memory block
}
#endif
```
Of course, calls to crashHandler() should be synchronizes system-wide (by QSystemSemaphore, for example)

**Comment by retmas** [comment]
> Upon shutting down, the primary instance needs to do some clean up and mark itself as shut down in the shared memory.

Upon normal shutting down, it does clean up.
After crash, the new process will clean up remaining shared memory object. And that's ok. Because in general it can't be done upon abnormal shutting down(N.B. SIGKILL)

**Comment by itay-grudev** [comment]
Secondary Instance is the ability of the library to break the singleton model and have a second process of your app running. The library also includes a messaging system from the secondary instance to the primary.

The primary instance is the first process started. Every process started afterwards is a secondary instance. This feature can be disabled and is extremely useful when you want to do some custom behaviour upon the user spawning a new instance. Example: send the arguments supplied to the new instance to the primary instance.

**Comment by retmas** [comment]
I see. that's ok. It is still can be thought as a kind of singleton (by logic but not technically). By mean of application singleton that is not just a process(kernel object), but an "eco-system". Am i right?

**Comment by retmas** [comment]
Sorry if it is not clear what i am talking about as of my poor english (was about to write pure:-)
