### ISSUE TITLE
System wide not works on windows

### ISSUE THREAD

**Issue by hojjatjafary** [itay-grudev/SingleApplication#27]
I created an application this way:
```C++
SingleApplication app(argc, argv, false, SingleApplication::Mode::System);
```
but single application only works for a single user account on windows, I tested the calculator example you can open two instance with two different user account but each one can open only a single one.
Seems it requires that the shared memory key prefixed with "Global\".
you can find more info about it [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa366551(v=vs.85).aspx).
it should also be done for the [SystemSemaphore](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682446(v=vs.85).aspx).
I tried doing so by calling `setNativeKey` but no luck:
```C++
QSharedMemory *memory = new QSharedMemory();
memory->setNativeKey("Global\\" + d->blockServerName);
d->memory = memory;
```
the application can not create shared memory neither attach it.

GL.

**Comment by itay-grudev** [comment]
> Note: Operating system can restrict the shared memory blocks to the same user, in which case the User/System modes will have no effect and the block will be user wide.

I added support for it from the library, but AFAIK I cannot override OS behaviour unfortunately.

**Comment by hojjatjafary** [comment]
I found a way that works on windows:
```C++
QSharedMemory *memory = new QSharedMemory();
memory->setNativeKey("Global\\" + d->blockServerName);
d->memory = memory;
```
But the app should Run As Administrator, In this way there is only one instance system wide on windows.

**Comment by itay-grudev** [comment]
What happens if it is ran without administrative privileges?

**Comment by itay-grudev** [comment]
Just standard User Wide lock?

**Comment by hojjatjafary** [comment]
This should be done only when the `SingleApplication::Mode::System` is set. With the above code if you run with standard privilege, application will be closed immediately with exit code (0) because no shared memory can be created because of permission errors and also cannot attach one. 
As far as I know there are two options:
1. User of the library should be informed about System mode and use it by his own risk, they should run their app as admin by adding a manifest file to their executable.
2. We can fallback to User mode when it cannot run in System mode.

**Comment by itay-grudev** [comment]
My library is not responsible for user notifications. In fact it should work equally well on a console app. So only 2 may be a viable option. I'll give it some thought.

**Comment by hojjatjafary** [comment]
By first option I don't mean the end user I mean the programmer that uses your library and it can be mentioned in the documentation not the runtime app. ;)
Anyway the second option is more robust I think.
