### ISSUE TITLE
How can I restart my application when I use SingleApplication

### ISSUE THREAD

**Issue by coooooooooorey** [itay-grudev/SingleApplication#32]
``` C++
QTimer::singleShot(0, this, &CApplication::quit);
   
QProcess::startDetached(qApp->applicationFilePath(), {}, qApp->applicationDirPath());
```

I added this to my app. 

and this is how I `SingleApplication(argc, argv, true, ExcludeAppPath)` construct it.

I just couldn't make it restart.

But it works with QApplication.

Would you please help

**Comment by coooooooooorey** [comment]
Qt 5.9
macOS

**Comment by coooooooooorey** [comment]
Sorry. My mistake.

**Comment by itay-grudev** [comment]
This looked like a legit problem to me and did make sense. How did you fix it?

**Comment by coooooooooorey** [comment]
It would be great if you can implement this feature internally.

I closed this because I thought the execute file is missing dependence. 

 But it was strange that it works fine when I just use QApplication
