### ISSUE TITLE
Examples don't compile out-of-the-box with Qt 5.9.1

### ISSUE THREAD

**Issue by arette** [itay-grudev/SingleApplication#33]
`rts1-12:/opt/Qt/QtSingleApplication/examples/basic> qmake
Info: creating stash file /opt/Qt/QtSingleApplication/examples/basic/.qmake.stash
rts1-12:/opt/Qt/QtSingleApplication/examples/basic> ls
basic.pro  main.cpp  Makefile
rts1-12:/opt/Qt/QtSingleApplication/examples/basic> make
g++ -c -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQAPPLICATION_CLASS=QCoreApplication -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../../../QtSingleApplication -I../../../5.9.1/gcc_64/include -I../../../5.9.1/gcc_64/include/QtGui -I../../../5.9.1/gcc_64/include/QtNetwork -I../../../5.9.1/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../../5.9.1/gcc_64/mkspecs/linux-g++ -o singleapplication.o ../../singleapplication.cpp
../../singleapplication.cpp: In static member function ‘static void SingleApplicationPrivate::terminate(int)’:
../../singleapplication.cpp:243:37: error: ‘QApplication’ has not been declared
         delete ((SingleApplication*)QApplication::instance())->d_ptr;
                                     ^
make: *** [singleapplication.o] Error 1
`

**Comment by itay-grudev** [comment]
Did you set the QAPPLICATION_CLASS macro?

**Comment by arette** [comment]
I just tried building the provided examples without making any changes

**Comment by arette** [comment]
I was able to adapt to get it working for my application, this is just more of a heads-up to you that the provided examples need updating

**Comment by arette** [comment]
thank you for this package btw - it was critical in porting our old Qt3 app in a timely manner!

**Comment by itay-grudev** [comment]
Argh. I'll add it to my TODO list. But chances are I won't be able to take a look at it any time soon. Sorry.

**Comment by itay-grudev** [comment]
@arette I'm glad it was useful.
