### ISSUE TITLE
Signal handlers used by SingleApplication on Unix-like systems prevent core dumps / crash reports when the process crashes

### ISSUE THREAD

**Issue by jlarcombe** [itay-grudev/SingleApplication#35]
Because SingleApplication installs handlers for all the common signals, the default signal handler is never called in the event of (say) a segmentation fault, and hence the platform's usual crash reporting / core dump mechanism is never triggered. Instead, exit is called, which counts as a 'normal' process termination.

This is something I've noticed on Mac OS X, where the crash reporter doesn't get chance to do its job, but I think this would also apply if core dumps were enabled on Linux for example.

Also I believe related: I've seen some crash logs showing an infinite loop in `SingleApplication::terminate`, where it calls `exit`, which tries to free some allocated memory which happens to fail. This then calls abort and goes back to terminate again, and so on. In this case the process eventually dies from stack exhaustion, I assume, and we do get a log. But obviously this doesn't reveal much about the original source of the problem.

I think a solution would be to store the default signal handlers somewhere when they are replaced in `crashHandler()` and then reset them in the terminate function before re-raising the original signal, rather than calling exit.

**Comment by itay-grudev** [comment]
Thanks. I'll give it some thought.

**Comment by jlarcombe** [comment]
I did it like this, bit crude but seems to work: https://github.com/jlarcombe/SingleApplication/commit/cfb71c841278fe0f5c07c3af9d6b555e13f0be98

**Comment by itay-grudev** [comment]
I'll review tomorrow or later next week, if that's ok.

**Comment by itay-grudev** [comment]
We no longer use signals in the latest version.
