### ISSUE TITLE
Partial Code Review and Feedback

### ISSUE THREAD

**Issue by jbuckmccready** [itay-grudev/SingleApplication#37]
Thanks for putting this lib/code together. 
When browsing the code I noticed some things:
1. There are numerous warnings from clang about c style casts (most/all of the pointer casts could just be static_casts, the others probably could be better served using QDataStream to avoid reinterpret casts), and about the possible use of an uninitialized value instanceId [here](https://github.com/itay-grudev/SingleApplication/blob/4f0365107283ce321da713baeab4d2aad0456baf/singleapplication.cpp#L321), I don't think it can be uninitialized at that point but the fall through on the switch is confusing it (and most likely others).
2. When writing the instanceId a quint32 is used ([here](https://github.com/itay-grudev/SingleApplication/blob/4f0365107283ce321da713baeab4d2aad0456baf/singleapplication.cpp#L217)) but only the little end byte is read back ([here](https://github.com/itay-grudev/SingleApplication/blob/4f0365107283ce321da713baeab4d2aad0456baf/singleapplication.cpp#L294)).
3. The checksum quint16 is needlessly converted to string using QByteArray::number, and QByteArray::number is given an invalid parameter for the base ([here](https://github.com/itay-grudev/SingleApplication/blob/4f0365107283ce321da713baeab4d2aad0456baf/singleapplication.cpp#L218) and [here](https://github.com/itay-grudev/SingleApplication/blob/4f0365107283ce321da713baeab4d2aad0456baf/singleapplication.cpp#L297-L300)). You pass in 256 for the second argument, but the Qt docs ([here](http://doc.qt.io/qt-5/qbytearray.html#number)) mention that the base can be any value between 2 and 36.
4. QLocalSocket::waitForReadyRead is used with the assumption that all data is available, according to the Qt docs not all data is guaranteed to be available see Qt's example [here](http://doc.qt.io/qt-5/qtnetwork-fortuneclient-example.html). Place in the code is [here](https://github.com/itay-grudev/SingleApplication/blob/4f0365107283ce321da713baeab4d2aad0456baf/singleapplication.cpp#L279). In practice considering the amount of bytes written and the fact that it's a local socket this is likely to never fail, but it's not air tight to the documentation.

**Comment by itay-grudev** [comment]
1: If you could produce equivalent code - PRs are welcome.

2:
```cpp
tmp = nextConnSocket->read( sizeof(quint32) ); // reads 4 bytes
const char * data = tmp.constData(); // gets a pointer to those 4 bytes
instanceId = (quint32)*data; // Casts those 4 bytes to quint32
```

3: It's not needlessly converted to a number. `qChecksum` returns a quint16 which in order to append to the QByteArray needs to be converted into a QByteArray. Though it seems like the QByteArray::number() method is incorrectly used as the documentation states that the base must be between 2 and 36. PRs welcome.

4: It is guaranteed for a valid connection as all the data will be flushed at once. But when it isn't (with an invalid connection) the validation code following would gracefully fail and the connection will be ignored.

Correct me if I'm wrong on points 2 and 4.

**Comment by jbuckmccready** [comment]
Hi, thanks for the reply!
For point 2:
`instanecId = (quint32)*data;` will dereference `data` as a `char` and then cast that `char` to a `quint32`. Wandbox example [here](https://wandbox.org/permlink/O7iI4fyippVfEaFh).

For point 3:
You can serialize and deserialize the quint16 to a byte array using [QDataStream](http://doc.qt.io/qt-5/qdatastream.html), here is a quick snippet:
```cpp
QByteArray bytes;
// write 42 as quint16 to byte array
QDataStream writeStream(&bytes, QIODevice::WriteOnly);
writeStream.setVersion(QDataStream::Qt_5_6);
quint16 val = 42;
writeStream << val;
// read quint16 from byte array
QDataStream readStream(bytes);
readStream.setVersion(QDataStream::Qt_5_6);
quint16 result = 0;
readStream >> result;
// result now equals 42
```

If I can find some time I'll try and put a PR together.

**Comment by itay-grudev** [comment]
On point 2, you are correct. It should be:

```cpp
instanceId = *(quint32*)data;
```

I'll update it when I have time. Or faster if you make a PR.

Thanks.

**Comment by jbuckmccready** [comment]
I'm working on a PR.
```cpp
instanceId = *(quint32*)data;
```
That snippet is also not valid since it breaks strict aliasing rules in the c++ standard (see [here](http://dbp-consulting.com/tutorials/StrictAliasing.html) for breakdown on strict aliasing). You have to use a memcpy to avoid undefined behavior, e.g.
```cpp
quint32 instanceId;
memcpy(&instanceId, data, 4);
```
Compiler will eliminate the memcpy call on optimized builds. All of these land mines can be avoided using QDataStream.

**Comment by jbuckmccready** [comment]
I made a pull request (#38). Note however that this is a "breaking" change in so much as the serialization/deserialization is no longer reading only one byte and QDataStream may format the data in a different order (e.g. big endian vs little endian). But with these changes we can now maintain a stable serialization format using the QDataStream version.
