### ISSUE TITLE
I had to add LIBS += User32.lib using msvc2017 Qt 5.9.2

### ISSUE THREAD

**Issue by jbuckmccready** [itay-grudev/SingleApplication#39]
This may be something funky/weird with my build setup but I had to add `msvc:LIBS += User32.lib` in my QMAKE project in addition to the `msvc:LIBS += Advapi32.lib` to use `AllowSetForegroundWindow(DWORD(app.primaryPid()));` with msvc 2017 64 bit building with Qt 5.9.2.

If others also have this issue it may make sense to add it to the .pri file.

**Comment by itay-grudev** [comment]
Yhea, but this is specific to your program. Not everyone may using the library for raising their application to the foreground so I don't think including it in the `.pri` is useful.

**Comment by EelcoPeacs** [comment]
A solution might be here to add a CONFIG option for convenience. Just change the code in the pri file at line 10 to

`win32 {
    msvc:LIBS += Advapi32.lib
    gcc:LIBS += -lAdvapi32
    CONFIG( USEFOREGROUND ) {
        msvc:LIBS += User32.lib
        gcc:LIBS += -lUser32
    }
}`

By specifying `CONFIG += USEFOREGROUND` in a project file the library can be easily added

**Comment by hojjatjafary** [comment]
Can you explain why you can not add the Windows libraries to the .pro file of your own project? I'm using the AllowSetForegroundWindow function too(Qt 5.9.0) but it is not required to add the libs in the .pri file of SingleApplication.

**Comment by jbuckmccready** [comment]
I understand now my confusion, I thought the Advapi32.lib was added in the .pri file to support `AllowSetForegroundWindow` but it is added for other dependencies in the singleapplication.cpp file. I misread the windows readme and thought it mentioned Advapi32.lib when it actually directly mentions linking User32.lib, oops.

**Comment by EelcoPeacs** [comment]
You can definitely add the library to the .pro file of your own project. I have added it there as well at the moment to be able to use the foreground function. But as can be seen from this discussion, it can support easy adaption of a new users project to meet all requirements.
So adding it to the .pri file, with default being disabled, does not harm the code for other platforms and/or use but may support easy incorporation of it if desired.
