### ISSUE TITLE
Fix listen on Unix after process crash

### ISSUE THREAD

**Issue by kklimek** [itay-grudev/SingleApplication#4]
https://github.com/itay-grudev/SingleApplication/blob/master/singleapplication.cpp#L26

From Qt docs:
Note: On Unix if the server crashes without closing listen will fail with AddressInUseError. To create a new server the file should be removed. On Windows two local servers can listen to the same pipe at the same time, but any connections will go to one of the server.

With current code you do not handle such behaviour

**Comment by itay-grudev** [comment]
On the contrary. That is exactly what the call of ```removeServer()``` is for.

**Comment by kklimek** [comment]
you should call removeServer ONLY in case of AddressInUseError - in other scenarios you should never call it

**Comment by itay-grudev** [comment]
@kklimek Incorrect. If a previous instance has crashed it will result in an ```AddressInUseError``` in the first place.

**Comment by itay-grudev** [comment]
This could only be done after an attempt to listen to the server + a check of the error. Ultimately the penalty is the same of either approach, but mine is simpler since it requires less amount of code.

**Comment by kklimek** [comment]
The penalty of your current code is that you can start two applications at once because you always remove the file. Otherwise you can still check if there is other instance in another step.

**Comment by kklimek** [comment]
I'm doing something like this:

	for	(int i = 0; i < 2; ++i) {
		if (d->otherInstanceIsRunning())
			return false;

		if (!d->localServer->listen(d->localSocketId())) {
			qDebug() << "Local server failed to listen!" << d->localServer->errorString();
			if (d->localServer->serverError() == QAbstractSocket::AddressInUseError) {
                                // allow code to check again
				continue;
			}
		}

		break;
	}

	if (!d->localServer->isListening()) {
		// From Qt docs:
		// Note: On Unix if the server crashes without closing listen will fail with AddressInUseError. To create
		// a new server the file should be removed. On Windows two local servers can listen to the same pipe at
		// the same time, but any connections will go to one of the server.
		QLocalServer::removeServer(d->localSocketId());
		if (!d->localServer->listen(d->localSocketId())) {
			qDebug() << "Another instance is probably running" << d->localServer->errorString();
			return false;
		}
	}

**Comment by kklimek** [comment]
bool ApplicationPrivate::otherInstanceIsRunning() const
    {
        // check if other instance is running
        QLocalSocket sock;
        sock.setServerName(localSocketId());
        sock.connectToServer();

    #ifdef Q_OS_WIN
        // allow foreground window from second instance
        // instead of playing with PID exchange we simply allow all
        AllowSetForegroundWindow(ASFW_ANY);
    #endif

        if (sock.waitForConnected(3000)) {
                sock.disconnect();
                sock.waitForDisconnected(3000);
                return true;
        }

    #ifdef Q_OS_WIN
        // allow only self, so no other app will cover us
        AllowSetForegroundWindow(GetCurrentProcessId());
    #endif

	  return false;
    }

**Comment by tilor** [comment]
As I get it you connect to QLocalSocket() in case the local server crashed - in order to only exit if the other instance really is available.
However in the else-case the program is also terminated.
Is that a mistake or by purpose?

```
        if( d_ptr->socket->waitForConnected(100) )
        {
            ::exit(EXIT_SUCCESS); // Terminate the program using STDLib's exit function
        } else {
            delete d_ptr->memory;
            ::exit(EXIT_SUCCESS);  //--> Why is exit called in else?
        }
```

**Comment by itay-grudev** [comment]
The existence of a `QSharedMemory` block (with some exceptions) guarantees the existence of a parent process, while the fact that the `QLocalSocket` did not connect does not guarantee that the parent process has crashed. It might just be doing some heavy computation and cannot respond to the request. For this reason, even though the notification to the parent process was not successful I sill terminate the program.

**Comment by tilor** [comment]
Thanks for your quick reply!
Your current solution works perfectly on Windows. I came to that issue when I ran the same code on Mac: There, if I debug the program and then stop the debugger, the crashHandler() does not get called and so the QSharedMemory stays there forever.
My personal solution now was to keep the ::exit() in the else-case on Windows, but not on OS X.

**Comment by itay-grudev** [comment]
Can you give the return code when your application crashes?

**Comment by tilor** [comment]
No, my application does not crash: I am debugging through the code in Qt Creator and then just press stop. This causes the program to immediately terminate and the crashHandler has no chance to remove the Shared Memory.

**Comment by itay-grudev** [comment]
I meant the exit code.

**Comment by itay-grudev** [comment]
@tilor @kklimek Hey guys. Just an update. The new version of the library recovers from crashes with ease on all OSs. This includes the case if it's killed on Linux/OS X/Unix and the `QSharedMemory` block is not deleted. By attaching it and then detaching it when there are no other instances will cause the memory to be released.
