### ISSUE TITLE
Make it independent from Q*Application

### ISSUE THREAD

**Issue by agateau** [itay-grudev/SingleApplication#44]
Having looked at the code, it seems to me that the SingleApplication class has no reason for inheriting from one of the Q*Application classes. Making it inherit from QObject would avoid the need for the `QAPPLICATION_CLASS` define.

Is there any reason for this inheritance, or could it be removed?

**Comment by itay-grudev** [comment]
I designed it to be a drop in replacement for the `QApplication`* class and I wanted to be able to avoid entering the Qt event loop in the first place. And since initialising `QApplication`* is the first thing a qt app does, it seemed reasonable.

**Comment by itay-grudev** [comment]
I'll think about it for the next major version though.
