### ISSUE TITLE
Sending message not always working

### ISSUE THREAD

**Issue by pawelsalawa** [itay-grudev/SingleApplication#47]
# The issue

I found out the sendMessage() to fail (message not delivered) randomly (roughly in 50% of cases) if any of following is met:

- Linux (Ubuntu) with Qt older than 5.6.3 (I edited QDataStream data version enumerations to 5.3 in the code)
- MacOSX, probably for all Qt versions (I've tried with Qt 5.10).

I tested it with the example application "sending_arguments", just to be sure and yes, it's reproducible with that sample project.

# The solution

I also found out a quick solution.

1. Add `#include <QThread>` in singleapplication.cpp
2. Add `QThread::msleep(100);` in the same file, in method `sendMessage()`, right after the line `d->connectToPrimary( timeout,  SingleApplicationPrivate::Reconnect );`

Maybe not the most elegant way, but hey, at least it works. I'm not sure why Qt fails to wait required time and to be honest I did not have time to digg into it deeply enough.

**Comment by itay-grudev** [comment]
This is caused by another bug #46. I already have a PR with a fix for it. I'll merge it ASAP.

**Comment by itay-grudev** [comment]
I'll leave this open until I fix it.

**Comment by itay-grudev** [comment]
This should be resolved now.
