### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by emericg** [itay-grudev/SingleApplication#52]
Hi!
I'm using SingleApplication in one of my application and it's working great. I recently tried running that application on Android and iOS. It was seamless... except I had to manually disabled SingleApplication with ifdefs in order for the application to start.

Feature wise, SingleApplication doesn't really make sense in mobile apps anyway, but it would be super nice if it could (transparently) behave as a regular qapplication instead of crashing the app!

The only debug output that I have says: 
`W WatchFlower: (null):0 ((null)): Unimplemented code.`
So I get that this is not very helpful, sorry, but I'm available if you need more infos or tests.

**Comment by LNJ2** [comment]
I'll probably get the same problem in the next build for android...

**Comment by itay-grudev** [comment]
> Feature wise, SingleApplication doesn't really make sense in mobile apps anyway, but it would be super nice if it could (transparently) behave as a regular qapplication instead of crashing the app!

Is it possible that Qt hasn't implemented something for mobile? Maybe one of the Qt classes I am using? I am not familiar with Qt for mobile, so any assistance from you guys will be greatly appreciated.

I suppose, since the singleton model is build in most mobile OSes we can conditionally  `return` in the SingleApplication constructor if it's on mobile and allow the library to "gracefully" fail.

**Comment by emericg** [comment]
It seems that QSharedMemory is just not there on Android.

Again it's just a matter of using the same code on all platforms and not having to figure out where to put ifdef when encountering a cryptic error. With Qt for android you just have to switch to an android kit and everything else is transparent.

**Comment by itay-grudev** [comment]
I'd love some feedback here from other people before I decide how to handle this issue.

**Comment by dilshodm** [comment]
I think this is the best

>  but it would be super nice if it could (transparently) behave as a regular qapplication instead of crashing the app

**Comment by itay-grudev** [comment]
Can you guys verify this is the behaviour you wanted and it works OK with you?

I don't have a setup to even compile this for Android at the moment.

**Comment by emericg** [comment]
Yes thank you, I only did a quick test but it does work now with your patch!
I'll close this as soon as I can test a few more cases.

**Comment by emericg** [comment]
Ok good for me, you can close this one at your convenience.
Actually it also works for iOS too (same problem than Android before, crashing during startup) with just #if defined(Q_OS_ANDROID) || defined(Q_OS_IOS)
