### ISSUE TITLE
Shared memory problem on armhf

### ISSUE THREAD

**Issue by pbek** [itay-grudev/SingleApplication#58]
I've got a weird case on a armhf system. (see https://github.com/pbek/QOwnNotes/issues/1089)
I'm not sure if it is the setup of the user or a problem with armhf in general.

```
Critical: SingleApplication: Unable to attach to shared memory block. ((null):0, (null))
Critical: "QSharedMemoryPrivate::initKey: unable to set key on lock" ((null):0, (null))
```

**Comment by itay-grudev** [comment]
Hey mate, I'm really busy right now. The earlierst I can look into this is Monday. But if for some reason I forget remind me on itay[]grudev.com

**Comment by pbek** [comment]
No problem. I'm not sure you can do anything about it.
Have a busy weekend. :smile:

**Comment by itay-grudev** [comment]
It looks like a Qt problem though.

**Comment by pbek** [comment]
Yes, everything seems to be legitimate in https://github.com/itay-grudev/SingleApplication/blob/2fac2a38040e8996d2a91e8f043dcfb924893d5b/singleapplication.cpp#L69-L74

**Comment by itay-grudev** [comment]
If you have time, can you create an issue in the Qt bug tracker. Somebody there might know the cause of the problem.

**Comment by itay-grudev** [comment]
Was this caused on a Raspberry Pi 3?

**Comment by pbek** [comment]
> Was this caused on a Raspberry Pi 3?

No, a container: `linux ubuntu 16.04 container`

**Comment by pbek** [comment]
I'm still in the process of investigating...

**Comment by itay-grudev** [comment]
See if you can find anything about problems with QSharedMemory and QSystemSemaphore on `arm` architectures. Maybe they only have a limited or incomplete implementation.

Signing off for now.

**Comment by pbek** [comment]
Thank you, have a great rest of your day!

**Comment by itay-grudev** [comment]
#52

**Comment by pbek** [comment]
(I'll remind you on my two pull requests later. :smile: )

**Comment by pbek** [comment]
> #52

yes, maybe that's related...

**Comment by pbek** [comment]
I attempted to implement a check if shared memory will work in `SingleApplication` in commit <https://github.com/pbek/QOwnNotes/commit/23869cbcb78a2b767a4032b6de94bf6b5cc8ab8f>, in case you are interested. :wink:

**Comment by itay-grudev** [comment]
I messaged your guy and asked about kernel version and CPU details. I think that may be relevant in reproducing the issue.

**Comment by itay-grudev** [comment]
@pbek Feedback to fix = 8 hours. You're awesome.

**Comment by pbek** [comment]
...or insane? :smile:
