### ISSUE TITLE
Uninitialized variables in the constructor

### ISSUE THREAD

**Issue by Shatur95** [itay-grudev/SingleApplication#60]
SingleApplicationPrivate has members that are not initialized in the constructor: [memory](https://github.com/itay-grudev/SingleApplication/blob/b24d5394a580930919d207683c03954aaafd0e54/singleapplication_p.h#L85) and [instanceNumber](https://github.com/itay-grudev/SingleApplication/blob/b24d5394a580930919d207683c03954aaafd0e54/singleapplication_p.h#L88). This is unsafe.
For example, PVS Studio and CppCheck issue a warning about this. I suggest initializing `memory` with `nullptr` and `instanceNumber` with -1.

**Comment by itay-grudev** [comment]
Resolved in `v3.0.14`.

https://github.com/itay-grudev/SingleApplication/blob/adac9a30aa82a03a85d66c6d98836d7a122d2978/singleapplication_p.cpp#L53-L60
