### ISSUE TITLE
feature? add option for create different SingleApplication with different id.

### ISSUE THREAD

**Issue by Yue-Lan** [itay-grudev/SingleApplication#78]
Hi, Itay.

I found that SingleApplication has a limitation of creating different "primary" app Instances.

The situation I met is that I have to create two progresses and they are both primary, but not same at all (each one can be see as a normal SingleApplication and can get message from secondary one).

My solution is add an optional argument for generating socket channel by this argument. [see here](https://github.com/explorer-cs/peony-qt/commit/84c5da445b8b9c5908f0a8af728bf9b4ee281635)

This project is very helpful for my works. I'm not sure it is a good idea for your project. I just used it and list which I've thought.

Cheers.

**Comment by itay-grudev** [comment]
@Yue-Lan When you launch your app how do you decide whether it's primary1 or primary2?

P.S. I apologise for the late response.

**Comment by Yue-Lan** [comment]
Thanks for response.

I'm not sure if I described it well. 

I have 1 project but 2 different apps A and B using SingleApplication, and I should keep them both being 'single'.

The primary1(app1) is autostarted, and run all the time. The  primary2(app2) will start when it was needed. So the primary1 and primary2 is Unassociated.

If I just derived App1 and App2 from SingleApplication, They'll be incompatible. This is a problem that multi-projects use SingleApplication may occuer.

**Comment by itay-grudev** [comment]
But if they are different projects, they will get different `genBlockServerName`s and there shouldn't be a colision. Whether you run them with secondary instance support is up to you.

**Comment by itay-grudev** [comment]
Also the block server name depends on the following:

https://github.com/itay-grudev/SingleApplication/blob/16ea64b2548b02f59bf49b255466278c3ff0ace8/singleapplication_p.cpp#L86-L135

**Comment by Yue-Lan** [comment]
I see, maybe I should set different application’s name by qapplication’s method. I usually not do that... I will follow your advice. thanks a lot.
