### ISSUE TITLE
How can we regard different cmd line of same application as different instance 

### ISSUE THREAD

**Issue by 578141611** [itay-grudev/SingleApplication#79]
I have an app support different cmd line,but they all been regarded as same install.

**Comment by itay-grudev** [comment]
If you change the `applicationName` based on the command line parameters, that would do the trick. See #78

**Comment by 578141611** [comment]
Thank you for your reply.In my opinion , I think we can generate information from cmd line ,then distingush differernt cmd line but same console application. I find solution in another project.
