### ISSUE TITLE
Can not support cross-session on windows platform

### ISSUE THREAD

**Issue by 578141611** [itay-grudev/SingleApplication#80]
I want a single app on windows no matter which user session,but can not now.Wish your reply.thank you.

**Comment by itay-grudev** [comment]
See (Single Application Flags](https://github.com/itay-grudev/SingleApplication#flags) and the `Mode::System` in particular to force a system-wide block (independent of user session).

I believe that should do it, but I don't know how Windows will work when you launch the app under a different user. I suppose it will pass along the message and inform the primary instance, but you most certainly won't be able to raise it's window. :D

**Comment by 578141611** [comment]
Thank you for your rely.There is requirement in our product that we can only run a console applicaiton backgroud invisibly,even if switching user.This application is not system service. I have find solution in another qt single app solution which using global mutex on windows.

**Comment by itay-grudev** [comment]
As I said this one supports a global lock as well, but you have to raise the `Mode::System` flag upon initialisation. Anyway I'm closing this for now.
