### ISSUE TITLE
QTime elapsed is deprecated

### ISSUE THREAD

**Issue by lhy0403** [itay-grudev/SingleApplication#81]
Same as title, as the Qt 5.14.0 is released, the `elapsed()` signal in `QTime` has been marked as deprecated.

The solution to avoid receiving this warning is to use the `QElapsedTimer`
I think there's no need to change too much code, just add include and change the type of the timer from `QTime` to `QElapsedTimer` at here 
https://github.com/itay-grudev/SingleApplication/blob/16ea64b2548b02f59bf49b255466278c3ff0ace8/singleapplication.cpp#L85

**Comment by itay-grudev** [comment]
Thank you. I'll add it to my TODO list.

**Comment by lhy0403** [comment]
Thanks!

**Comment by itay-grudev** [comment]
This is now resolved.
