### ISSUE TITLE
qsrand is deprecated -> use QRandomGenerator instead

### ISSUE THREAD

**Issue by wangwenx190** [itay-grudev/SingleApplication#83]
https://github.com/itay-grudev/SingleApplication/blob/16ea64b2548b02f59bf49b255466278c3ff0ace8/singleapplication.cpp#L102

At least in Qt 5.14.0 `qsrand` is marked as deprecated. Qt documentation suggests use `QRandomGenerator` as its replacement.

**Comment by itay-grudev** [comment]
@wangwenx190 Is it a warning of a compile error? I'm asking to understand the priority of the issue.

**Comment by wangwenx190** [comment]
I didn't get any warning message or compile error when using `qsrand`, but the function itself does mark as deprecated in the documentation of Qt. It may be a low priority issue.

**Comment by variar** [comment]
Hi,

This will generate a warning with something like -Wall -Wextra, and the build will then fail if -Werror is set. Not sure how many projects use these, but it will break my travis ci builds on macos as soon as new qt version becomes available there.

I'll try to make a PR to fix the issue today. However, QRandomGenerator was introduced in Qt 5.10, and Ubuntu 18.04 LTS still uses Qt 5.9, so I'm afraid that I'll have to use Qt version checking macros to support old and new style.
