### ISSUE TITLE
Question: is this per user, or per computer?

### ISSUE THREAD

**Issue by paulharris** [itay-grudev/SingleApplication#9]
The documentation doesn't say,
although I'd assume its per-computer?

ie shared-memory and local-server is visible for all users logged into the computer.

**Comment by itay-grudev** [comment]
Really good question. I've never thought about that. The current implementation of the library should prevent instances on the same system. Though I suppose it could be easily made to work an a user level by adding the user name to the shared memory key. Is that a feature you would like to have?

**Comment by paulharris** [comment]
I won't be using it just yet, but I have starred the project for future.
I would be using it for a program that sits in the Systray on the user's desktop in Windows / Linux.
Think, pidgin, that chat program.  Or a backup program.
You'd only want to have one program running (auto-started via Startup).
If user can't see it in Systray (even through its there), and runs the program a second time via shortcut, you can imagine confusion and even data corruption as the two programs write to the same files (each assuming THEY are the only one).

On a Linux desktop (thin-server-style), or Windows Terminal Server, you'll have multiple users with their own independent desktops.
You would want each user to be able to run the program once per desktop.  Which in 99.9% of cases boils down to "once per user".

**Comment by itay-grudev** [comment]
The new version of the library support a hint to specify whether you would like the block to be user-wide or system wide. Note that because the library works with a Shared Memory block, if the OS does not allow for the Shared Memory to be exposed to other uses the flag will have no effect and the block will be user-wide.
