### ISSUE TITLE
Make it possible to get the username of the primary application

### ISSUE THREAD

**Issue by autoantwort** [itay-grudev/SingleApplication#95]
When a user starts the application and the application is already running, the running application gets the focus. But when the application was started on a different user account, I want to show a message box with a text like `The application is already running by user ...`. Currently the application simply closes and the user is confused. 

So a function like `primaryUser()` would be cool. And something like `currentUser()` or `primaryStartedByDifferentUser()`.

**Comment by itay-grudev** [comment]
This shouldn't be the case unless you're using the `Mode::System` flag. By default it is scoped to a user and it works by including the username in the shared memory block name.

To add some extra custom logic on top of the standard singleton functionality you can use the secondary instance support.

It would work like this:

```
int main(int argc, char *argv[])
{
    SingleApplication app( argc, argv, true ); // <-- true here means allow secondary instance support

    if( app.isSecondary() ) {
        std::cout << "App already running by another user".
        app.exit( 0 );
    }

    return app.exec();
}
```

But you're right that when running in `Mode::System` it would be useful.

**Comment by autoantwort** [comment]
Yeah I am using the `Mode::System` flag. I can show a massage box every time, but when the app is running on the same user account, bringing the app to the front and showing a message box saying something is wrong is not an intuitive behavior.

**Comment by itay-grudev** [comment]
Give me 30min.

**Comment by itay-grudev** [comment]
It's actually slightly more complicated.

**Comment by autoantwort** [comment]
Can you not simply add a char array of length 50? to the InstancesInfo struct? And and int for the real length of the username string.

**Comment by itay-grudev** [comment]
Give it a go: https://github.com/itay-grudev/SingleApplication/releases/tag/v3.1.0a

**Comment by autoantwort** [comment]
Cool! Thank you! Only a function like 
```
QString SingleApplication::currentUser()
{
    Q_D(SingleApplication);
    return QString::fromLocal8Bit(d->getUsername()); // d->currentUser();
}
```
is needed to check if the current user is the primary use.
